#pragma once

const int PRIORITY_TILE = 0;
const int PRIORITY_RESOURCE = 500;
const int PRIORITY_BUILDING = 1000;
const int PRIORITY_UNIT = 1500;
const int PRIORITY_MENU = 2000;

enum
{
	TYPE_EMPTY,
	TYPE_TILE_GRASS,
	TYPE_TILE_SAND,
	TYPE_TILE_WATER,
	TYPE_UNIT_WARRIOR,
	TYPE_UNIT_RANGER,
	TYPE_RESOURCE_RAW_WOOD,
	TYPE_RESOURCE_RAW_STONE,
	TYPE_OBJECT_MENU_ACTION,
	TYPE_OBJECT_MENU_STAT,
};
