#pragma once

enum
{
    MSG_GET_PHYSICS,
    MSG_GET_GRAPHICS,
    MSG_GET_INPUT,
    MSG_DATA_PHYSICS_X_POS,
    MSG_DATA_PHYSICS_Y_POS,
    MSG_DATA_PHYSICS_Z_POS,
    MSG_DATA_PHYSICS_VELOCITY,
    MSG_DATA_GRAPHICS_SCREEN_POS_X,
    MSG_DATA_GRAPHICS_SCREEN_POS_Y,
    MSG_DATA_GRAPHICS_OFFSET_X,
    MSG_DATA_GRAPHICS_OFFSET_Y,
    MSG_DATA_GRAPHICS_TEXTURE_TYPE,
    MSG_DATA_GRAPHICS_FLIP,
    MSG_DATA_GRAPHICS_ZOOM,
    MSG_DATA_INPUT_SELECTED,
    MSG_SET_PHYSICS_X_POS,
    MSG_SET_PHYSICS_Y_POS,
    MSG_SET_PHYSICS_Z_POS,
    MSG_SET_PHYSICS_VELOCITY,
    MSG_SET_GRAPHICS_SCREEN_POS_X,
    MSG_SET_GRAPHICS_SCREEN_POS_Y,
    MSG_SET_GRAPHICS_OFFSET_X,
    MSG_SET_GRAPHICS_OFFSET_Y,
    MSG_SET_GRAPHICS_TEXTURE_TYPE,
    MSG_SET_GRAPHICS_FLIP,
    MSG_SET_GRAPHICS_ZOOM,
    MSG_SET_INPUT_SELECTED
};

